config/routes.rb
Cinemanager::Application.routes.draw do
  resources :cinemas_movies

  resources :cinemas

  resources :movies

   root :to => 'movies#index'

end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
  attr_accessible :active, :address, :name, :phone
  validates :name, :uniqueness => true
  has_and_belongs_to_many :movies
end

app/models/cinemas_movie.rb
class CinemasMovie < ActiveRecord::Base
  attr_accessible :active, :cinema_id, :movie_id, :mon, :tue, :wed, :thu, :fri, :sat, :sun
  validates_uniqueness_of :movie_id, :scope => :cinema_id, :message => ' (%{value}) cinemas movie has already been created.'
  validates_presence_of :movie_id, :cinema_id

   def cinema_name
	  begin
	    Cinema.find(cinema_id).name.to_s
	  rescue ActiveRecord::RecordNotFound
	    'Cinema has been manually deleted'
	  end
	end

	def movie_name
	  begin
	    Movie.find(movie_id).title.to_s
	  rescue ActiveRecord::RecordNotFound
	    'Movie has been manually deleted'
	  end
	end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :active, :cast, :details, :director, :rating, :reviews, :title
  has_and_belongs_to_many :cinemas
  validates :title, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  # GET /cinemas
  # GET /cinemas.json
  def index
    @cinemas = Cinema.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @cinemas }
    end
  end

  # GET /cinemas/1
  # GET /cinemas/1.json
  def show
    @cinema = Cinema.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @cinema }
    end
  end

  # GET /cinemas/new
  # GET /cinemas/new.json
  def new
    @cinema = Cinema.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @cinema }
    end
  end

  # GET /cinemas/1/edit
  def edit
    @cinema = Cinema.find(params[:id])
  end

  # POST /cinemas
  # POST /cinemas.json
  def create
    @cinema = Cinema.new(params[:cinema])

    respond_to do |format|
      if @cinema.save
        format.html { redirect_to @cinema, :notice => 'Cinema was successfully created.' }
        format.json { render :json => @cinema, :status => :created, :location => @cinema }
      else
        format.html { render :action => "new" }
        format.json { render :json => @cinema.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cinemas/1
  # PUT /cinemas/1.json
  def update
    @cinema = Cinema.find(params[:id])

    respond_to do |format|
      if @cinema.update_attributes(params[:cinema])
        format.html { redirect_to @cinema, :notice => 'Cinema was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @cinema.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cinemas/1
  # DELETE /cinemas/1.json
  def destroy
    @cinema = Cinema.find(params[:id])
    @cinema.destroy
    CinemasMovies.where(:cinema_id => params[:id]).each do |cinemas_movies|
      cinemas_movies.destroy
    end

    respond_to do |format|
      format.html { redirect_to cinemas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/cinemas_movies_controller.rb
class CinemasMoviesController < ApplicationController
  # GET /cinemas_movies
  # GET /cinemas_movies.json
  def index
    @cinemas_movies = CinemasMovie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @cinemas_movies }
    end
  end

  # GET /cinemas_movies/1
  # GET /cinemas_movies/1.json
  def show
    @cinemas_movie = CinemasMovie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @cinemas_movie }
    end
  end

  # GET /cinemas_movies/new
  # GET /cinemas_movies/new.json
  def new
    @cinemas_movie = CinemasMovie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @cinemas_movie }
    end
  end

  # GET /cinemas_movies/1/edit
  def edit
    @cinemas_movie = CinemasMovie.find(params[:id])
  end

  # POST /cinemas_movies
  # POST /cinemas_movies.json
  def create
    @cinemas_movie = CinemasMovie.new(params[:cinemas_movie])

    respond_to do |format|
      if @cinemas_movie.save
        format.html { redirect_to @cinemas_movie, :notice => 'Cinemas Movie was successfully created.' }
        format.json { render :json => @cinemas_movie, :status => :created, :location => @cinemas_movie }
      else
        format.html { render :action => "new" }
        format.json { render :json => @cinemas_movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @cinemas_movie = CinemasMovie.find(params[:id])

    respond_to do |format|
      if @cinemas_movie.update_attributes(params[:cinemas_movie])
        format.html { redirect_to @cinemas_movie, :notice => 'Cinemas Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @cinemas_movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @cinemas_movie = CinemasMovie.find(params[:id])
    @cinemas_movie.destroy

    respond_to do |format|
      format.html { redirect_to cinemas_movies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @movies }
      format.xml { render :xml => @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, :notice => 'Movie was successfully created.' }
        format.json { render :json => @movie, :status => :created, :location => @movie }
      else
        format.html { render :action => "new" }
        format.json { render :json => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, :notice => 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
     CinemasMovie.where(:movie_id => params[:id]).each do |cinemas_movies|
      cinemas_movies.destroy
    end

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/cinemas/_form.html.erb
<%= form_for @cinema, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :address, :class => 'text_area' ,:rows => 5%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :active, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :active, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cinemas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cinemas/edit.html.erb
<%- model_class = Cinema -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cinemas/index.html.erb
<%- model_class = Cinema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cinemas.each do |cinema| %>
      <tr>
        <td><%= link_to cinema.id, cinema_path(cinema) %></td>
        <td><%= cinema.name %></td>
        <td><%= cinema.active %></td>
        <td><%=l cinema.created_at %></td>
        <td>

          <%= link_to t('.view', :default => t("helpers.links.view")),
                      cinema_path(cinema), :class => 'btn btn-mini btn-info' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cinema_path(cinema), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cinema_path(cinema),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cinema_path,
            :class => 'btn btn-primary btn-success' %>

app/views/cinemas/new.html.erb
<%- model_class = Cinema -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cinemas/show.html.erb
<%- model_class = Cinema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @cinema.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @cinema.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @cinema.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @cinema.active %></dd>
</dl>

<h5> Movies Showing </h5>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cinema.movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.id, movie_path(movie) %></td>
        <td><%= movie.title %></td>
        <td><%= movie.active %></td>
        <td><%=l movie.created_at %></td>
        <td>
          <%= link_to t('.view', :default => t("helpers.links.view")),
                      movie_path(movie), :class => 'btn btn-mini btn-info' %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_movie_path(movie), :class => 'btn btn-mini' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      movie_path(movie),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cinemas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cinema_path(@cinema), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cinema_path(@cinema),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/cinemas_movies/_form.html.erb
<%= form_for @cinemas_movie, :html => { :class => 'form-horizontal' } do |f| %>
<div class="control-group">
    <%= f.label :movie_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select(:cinemas_movie, :movie_id, Movie.all, :id, :title, {:include_blank  => 'Select Movie'},:class=>"input-select")   %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cinema_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select(:cinemas_movie, :cinema_id, Cinema.all, :id, :name, {:include_blank  => 'Select Cinema'},:class=>"input-select")   %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :active, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :active, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mon, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mon, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tue, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tue, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :wed, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :wed, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :thu, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :thu, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fri, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fri, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sat, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sat, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sun, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sun, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cinemas_movies_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cinemas_movies/edit.html.erb
<%- model_class = CinemasMovie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cinemas_movies/index.html.erb
<%- model_class = CinemasMovie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:movie_id) %></th>
      <th><%= model_class.human_attribute_name(:cinema_id) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cinemas_movies.each do |cinemas_movie| %>
      <tr>
        <td><%= link_to cinemas_movie.id, cinemas_movie_path(cinemas_movie) %></td>
        <td><%= cinemas_movie.movie_name %></td>
        <td><%= cinemas_movie.cinema_name %></td>
        <td><%= cinemas_movie.active %></td>
        <td><%=l cinemas_movie.created_at %></td>
        <td>

          <%= link_to t('.view', :default => t("helpers.links.view")),
                      cinemas_movie_path(cinemas_movie), :class => 'btn btn-mini btn-info' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cinemas_movie_path(cinemas_movie), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cinemas_movie_path(cinemas_movie),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cinemas_movie_path,
            :class => 'btn btn-primary btn-success' %>

app/views/cinemas_movies/new.html.erb
<%- model_class = CinemasMovie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cinemas_movies/show.html.erb
<%- model_class = CinemasMovie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:movie_id) %>:</strong></dt>
  <dd><%= @cinemas_movie.movie_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cinema_id) %>:</strong></dt>
  <dd><%= @cinemas_movie.cinema_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @cinemas_movie.active %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mon) %>:</strong></dt>
  <dd><%= @cinemas_movie.mon %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tue) %>:</strong></dt>
  <dd><%= @cinemas_movie.tue %></dd>
  <dt><strong><%= model_class.human_attribute_name(:wed) %>:</strong></dt>
  <dd><%= @cinemas_movie.wed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:thu) %>:</strong></dt>
  <dd><%= @cinemas_movie.thu %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fri) %>:</strong></dt>
  <dd><%= @cinemas_movie.fri %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sat) %>:</strong></dt>
  <dd><%= @cinemas_movie.sat %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sun) %>:</strong></dt>
  <dd><%= @cinemas_movie.sun %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cinemas_movies_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cinemas_movie_path(@cinemas_movie), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cinemas_movie_path(@cinemas_movie),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :rating, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :director, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :director, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cast, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :cast, :class => 'text_area', :rows => 5  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :details, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :details, :class => 'text_area', :rows => 5 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reviews, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :reviews, :class => 'text_area', :rows => 5 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :active, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :active, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                movies_path, :class => 'btn' %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/new.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/show.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @movie.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @movie.rating %></dd>
  <dt><strong><%= model_class.human_attribute_name(:director) %>:</strong></dt>
  <dd><%= @movie.director %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cast) %>:</strong></dt>
  <dd><%= @movie.cast %></dd>
  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
  <dd><%= @movie.details %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reviews) %>:</strong></dt>
  <dd><%= @movie.reviews %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @movie.active %></dd>
</dl>



<h5> Cinemas Showing </h5>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @movie.cinemas.each do |cinema| %>
      <tr>
        <td><%= link_to cinema.id, cinema_path(cinema) %></td>
        <td><%= cinema.name %></td>
        <td><%= cinema.active %></td>
        <td><%=l cinema.created_at %></td>
        <td>

          <%= link_to t('.view', :default => t("helpers.links.view")),
                      cinema_path(cinema), :class => 'btn btn-mini btn-info' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cinema_path(cinema), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cinema_path(cinema),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              movies_path, :class => 'btn btn-info'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_movie_path(@movie), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              movie_path(@movie),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>